remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ABAV
logo: ./pic/web_logo.png
description: Arthropod-borne Associated Virus Database
